services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    environment:
      - "OLLAMA_MODELS=llama3.1"
    restart: unless-stopped
    volumes:
      - ./data/ollama_data:/ollama/data
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: missing
    volumes:
      - ./data/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 9000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=smartdev'
      - 'POSTGRES_PASSWORD=sa'
      - 'POSTGRES_USER=smartdev'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    restart: always
